name: vmaster
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      MASTER_PRE_RELEASE_ID: 36189658
      MASTER_PRE_RELEASE_TAG: vmaster
      ASSET_PATH: dist/FlyByWire_Installer_Setup.exe
      ASSET_NAME: FlyByWire_Installer_Setup.exe
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.9'
      - name: Set BUILT_DATE_TIME
        run: echo "BUILT_DATE_TIME=$(date -u -Iseconds)" >> $GITHUB_ENV
      - name: Install NPM dependencies
        run: npm ci

      - name: Install system requirements
        run: sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib && sudo dpkg --add-architecture i386 && wget -nc https://dl.winehq.org/wine-builds/winehq.key && sudo apt-key add winehq.key && sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main' && sudo apt update && sudo apt install --install-recommends winehq-stable

      - name: Package installer
        run: |
          npm run package && rm -rf ./dist/win-unpacked/
